name: Windows
on: 
  push:
    paths-ignore:
      - '*.md'
      - '*.bat'
      - '*.sh'
      - 'LICENSE'
      - '.clang-format'
      - '.gitignore'
      - 'doc/**'
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.bat'
      - '*.sh'
      - 'LICENSE'
      - '.clang-format'
      - '.gitignore'
      - 'doc/**'
jobs:
  build:
    name: Build
    # 运行平台， windows-latest目前是windows server 2019
    runs-on: windows-latest
    strategy:
      # 矩阵配置
      matrix:
        qt_ver: [5.12.6]
        qt_target: [desktop]
        qt_arch: [win64_msvc2017_64]
        msvc_arch: [x64]
    # 步骤
    steps:
      # 安装Qt
      - name: Install Qt
        # 使用外部action。这个action专门用来安装Qt
        uses: jurplel/install-qt-action@v2.0.0
        with:
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # Target platform for build
          target: ${{ matrix.qt_target }}
          # Architecture for Windows/Android
          arch: ${{ matrix.qt_arch }}
      # 拉取代码
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v1
        with:
            python-version: '2.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      # 编译msvc
#      - name: build-msvc-clang
#        shell: cmd
#        if: matrix.clang
#        env:
#          vc_arch: ${{ matrix.msvc_arch }}
#        run: |
#          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
#          set PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\LLvm\bin";%PATH%
#          qmake -spec win32-clang-msvc
#          nmake
      - name: build-msvc
        shell: cmd
#        if: false == matrix.clang
        env:
            vc_arch: ${{ matrix.msvc_arch }}
        run: |
          call "syncSkia.bat"
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" %vc_arch%
          qmake -spec win32-msvc "CONFIG+=release"
          nmake

